"""init

迁移 ID: b225ac5b3f67
创建时间: 2025-08-29 12:04:13.516505

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "b225ac5b3f67"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("activity_sessions",
    sa.Column("adapter", sa.String(length=50), nullable=False),
    sa.Column("scene_type", sa.String(length=50), nullable=False),
    sa.Column("scene_id", sa.String(length=100), nullable=False),
    sa.Column("count", sa.Integer(), nullable=False),
    sa.Column("last_session_activity", sa.DateTime(), nullable=True),
    sa.Column("last_bot_activity", sa.DateTime(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("adapter", "scene_type", "scene_id", name=op.f("pk_activity_sessions")),
    info={"bind_key": "nonebot_plugin_activity_tracker"}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity_sessions")
    # ### end Alembic commands ###
